# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notices', to='academics.student')),
            ],
            options={
                'verbose_name': 'إشعار دفع',
                'verbose_name_plural': 'إشعارات الدفع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balance', to='academics.student')),
            ],
            options={
                'verbose_name': 'رصيد رسوم',
                'verbose_name_plural': 'أرصدة الرسوم',
            },
        ),
    ]
