# Generated by Django 5.2.15 on 2026-06-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentdocument'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentnotice',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'إشعار دفع', 'verbose_name_plural': 'إشعارات الدفع'},
        ),
        migrations.AddField(
            model_name='paymentnotice',
            name='declared_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentnotice',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='studentfeebalance',
            name='access_override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='fee_plans', to='academics.grade')),
            ],
            options={
                'verbose_name': 'خطة رسوم',
                'verbose_name_plural': 'خطط الرسوم',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='studentfeebalance',
            name='fee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_balances', to='finance.feeplan'),
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.feeplan')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'أقساط',
                'ordering': ['order'],
                'unique_together': {('fee_plan', 'order')},
            },
        ),
    ]
