# Generated by Django 5.2.15 on 2026-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_paymentnotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinstallment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeinstallment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
