# Generated by Django 5.2.15 on 2026-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_feeinstallment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotice',
            name='source',
            field=models.CharField(choices=[('parent', 'من المنصة'), ('manual', 'يدوي')], default='parent', max_length=20),
        ),
    ]
