# Generated by Django 4.1.13 on 2026-08-18 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_feeinstallment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotice',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'], message='نوع الصورة غير مسموح')]),
        ),
    ]
