# Generated by Django 6.0.6 on 2026-06-15 08:16

import django.db.models.deletion
from django.db import migrations, models


def migrate_teacher_subjects(apps, schema_editor):
    Subject = apps.get_model("academics", "Subject")
    TeacherProfile = apps.get_model("staff", "TeacherProfile")
    for teacher in TeacherProfile.objects.all():
        name = (teacher.subject or "").strip()
        if not name:
            continue
        subject, _ = Subject.objects.get_or_create(name=name)
        teacher.teaching_subject_id = subject.id
        teacher.save(update_fields=["teaching_subject_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_subject"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="teaching_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teachers",
                to="academics.subject",
            ),
        ),
        migrations.RunPython(migrate_teacher_subjects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="subject",
        ),
    ]
