# Generated by Django 6.0.6 on 2026-06-15 08:25

from django.db import migrations, models


def migrate_subject_to_subjects(apps, schema_editor):
    TeacherProfile = apps.get_model("staff", "TeacherProfile")
    for teacher in TeacherProfile.objects.exclude(teaching_subject_id=None):
        teacher.teaching_subjects.add(teacher.teaching_subject_id)


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_subject"),
        ("staff", "0002_remove_teacherprofile_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="teaching_subjects",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="academics.subject"
            ),
        ),
        migrations.RunPython(migrate_subject_to_subjects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="teaching_subject",
        ),
    ]
