# Generated by Django 6.0.6 on 2026-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teacher_multiple_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
