# Generated by Django 4.1.13 on 2026-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_types_and_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم بالعربي'),
        ),
    ]
