# Generated by Django 6.0.6 on 2026-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'إدارة كلية'), ('admin_students', 'إدارة الطلاب'), ('admin_academics', 'إدارة الفصول والمواد'), ('admin_finance', 'إدارة المالية'), ('admin_content', 'إدارة المحتوى'), ('admin_staff', 'إدارة الكادر'), ('teacher', 'معلم'), ('parent', 'ولي أمر')], default='parent', max_length=30),
        ),
    ]
