# Generated by Django 4.1.13 on 2026-08-18 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_operational_academic_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
        migrations.AlterField(
            model_name='homeworkattachment',
            name='file',
            field=models.FileField(upload_to='homework/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
        migrations.AlterField(
            model_name='quizanswerattachment',
            name='file',
            field=models.FileField(upload_to='quiz/answer_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
        migrations.AlterField(
            model_name='subjectmaterialfile',
            name='file',
            field=models.FileField(upload_to='subject_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
    ]
