# Generated by Django 6.0.6 on 2026-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number', models.CharField(default='01', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'قيمة مدرسية',
                'verbose_name_plural': 'القيم المدرسية',
                'ordering': ['order'],
            },
        ),
    ]
