# Generated by Django 5.2.15 on 2026-06-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newsitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='news/gallery/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.newsitem')),
            ],
            options={
                'verbose_name': 'صورة خبر',
                'verbose_name_plural': 'صور الأخبار',
                'ordering': ['order', 'id'],
            },
        ),
    ]
