# Generated by Django 5.2.15 on 2026-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_welcome', models.CharField(default='مرحبا بكم في', max_length=200)),
                ('hero_school_name', models.CharField(default='مدرسة غَزتنا', max_length=200)),
                ('hero_tagline', models.CharField(default='التعليم الرقمي بمعايير عالمية', max_length=300)),
                ('hero_description', models.TextField(default='من أصالة الانتماء إلى ريادة المستقبل — منصة تعليمية حديثة تجمع بين التميز الأكاديمي والتقنية، لبناء جيل واعٍ ومبدع في غزة')),
                ('hero_cta_primary', models.CharField(default='ابدأ رحلتك', max_length=100)),
                ('hero_cta_secondary', models.CharField(default='تعرّف علينا', max_length=100)),
                ('about_description', models.TextField(default='مدرسة غَزتنا مؤسسة تعليمية رقمية تهدف إلى تمكين الطلاب من خلال بيئة تعلم آمنة، مبتكرة، ومتصلة بالمستقبل.')),
                ('about_vision', models.TextField(default='أن نكون المدرسة الرقمية الرائدة في فلسطين، نُخرّج جيلاً قادراً على المنافسة عالمياً مع الحفاظ على الهوية والقيم الوطنية.')),
                ('about_mission', models.TextField(default='توفير تعليم عالي الجودة يجمع بين المناهج الأكاديمية والمهارات الرقمية، مع دعم شامل لأولياء الأمور والمجتمع.')),
                ('contact_address', models.CharField(default='غزة، فلسطين', max_length=300)),
                ('contact_phone', models.CharField(default='+970 599 000 000', max_length=50)),
                ('contact_email', models.EmailField(default='info@ghazatna.edu.ps', max_length=254)),
                ('footer_tagline', models.CharField(default='منصة تعليمية رقمية تجمع بين التراث الفلسطيني والتقنية الحديثة.', max_length=300)),
                ('reg_show_notes', models.BooleanField(default=True)),
                ('reg_show_birth_date', models.BooleanField(default=True)),
                ('reg_grade_choices', models.JSONField(default=list, help_text='قائمة المراحل الدراسية المتاحة في فورم التسجيل. مثال: [{"value":"primary","label":"ابتدائي"}]')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
