# Generated by Django 5.2.15 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_admissions_and_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='programs_by_grade',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
