# Generated by Django 5.2.15 on 2026-06-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accreditation',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
