# Generated by Django 5.2.15 on 2026-06-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_grade'),
        ('staff', '0004_teacherprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='staff.teacherprofile'),
        ),
    ]
