# Generated by Django 5.2.15 on 2026-06-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_schoolclass_homeroom_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='academics.student')),
            ],
            options={
                'verbose_name': 'وثيقة طالب',
                'verbose_name_plural': 'وثائق الطلاب',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
