# Generated by Django 4.1.13 on 2026-08-18 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_student_contact_and_evaluation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='academics_student_unique_login_account',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='رقم جوال ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(upload_to='students/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'pdf', 'png', 'ppt', 'pptx', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip'], message='نوع الملف غير مسموح')]),
        ),
    ]
